#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import ffmpeg
import os
from pytube import YouTube
from gi.repository import GLib


class Downtube:
    DOWNLOAD_FOLDER = f"{GLib.get_user_special_dir(GLib.UserDirectory.DIRECTORY_DOWNLOAD)}/"
    def __init__(self, url):
        try:
            self.__pytube_object = YouTube(url)
        except Exception as e:
            print("Url invalid!. Type one url valid please.")
            return 1

    # Functions

    def download_audio(self):
        pytube_object = self.__pytube_object
        title_video = self.normalize_video_title()
        print(title_video,pytube_object.title)
        audio = pytube_object.streams.filter(only_audio=True, file_extension="mp4").first()
        audio.download(Downtube.DOWNLOAD_FOLDER,filename=title_video)
        os.rename(f"{Downtube.DOWNLOAD_FOLDER}{title_video}.mp4",
                  f"{Downtube.DOWNLOAD_FOLDER}{title_video}.mp3")
        print("Successfuly download!")
        return 0

    def download_video(self, quality):
        pytube_object = self.__pytube_object
        title_video = self.normalize_video_title()
        quality = f"{quality}p"
        self.download_video_and_audio(quality)
        Downtube.merge_video_and_audio(title_video)
        Downtube.delete_cache()
        print("Download successful!")

    def error_url(self, message):
        pytube_object = self.__pytube_object
        qualities_of_video = pytube_object.streams.filter(
            adaptive=True, file_extension="mp4", only_video=True)
        qualities = ""
        last_resolution = ""
        last_fps = 0
        for quality in qualities_of_video:

            if last_resolution == quality.resolution:
                if last_fps == quality.fps:
                    pass
                else:
                    qualities += f"{quality.resolution}    "
                    last_resolution = quality.resolution
                    last_fps = quality.fps
            else:
                qualities += f"{quality.resolution}    "
                last_resolution = quality.resolution
                last_fps = quality.fps

        return f"""{message}, the valid qualities are the following:
{qualities}"""

    def normalize_video_title(self):
        pytube_object = self.__pytube_object
        print(pytube_object.title)
        title_video = pytube_object.title
        # Change /
        normalized_title = title_video.replace("/", ":")
        # Delete dot "."
        normalized_title = normalized_title.replace(".", "")

        return normalized_title

    def download_video_and_audio(self, quality):
        try:
            pytube_object = self.__pytube_object
            video = pytube_object.streams.filter(file_extension="mp4", res=quality).first()
            video.download(filename="video", output_path=".cache/")
            audio = pytube_object.streams.filter(
                only_audio=True, file_extension="mp4").first()
            audio.download(filename="audio", output_path=".cache/")
        except Exception as e:
            print(self.error_url("Invalid quality"))
            quit()

    @classmethod
    def merge_video_and_audio(cls, title_video):
        video = ffmpeg.input(f".cache/video.mp4")
        audio = ffmpeg.input(f".cache/audio.mp4")

        out = ffmpeg.output(
            video, audio, f"{Downtube.DOWNLOAD_FOLDER}{title_video}.mp4", vcodec="copy", acodec="aac", strict="experimental")
        out.run()

    @classmethod
    def delete_cache(cls):
        os.remove(".cache/video.mp4")
        os.remove(".cache/audio.mp4")

def cli():
    parser = argparse.ArgumentParser(
        prog="Youtube Downloader",
        description="Youtube Downloader will help you to download video or audio of videos from youtube"
    )
    parser.add_argument(
        "--audio", "-a",
        action="store_true",
        help="Download audio of url"
    )
    parser.add_argument(
        "--video", "-v",
        action="store_true",
        help="Download video of url"
    )
    parser.add_argument(
        "--quality", "-q",
        type=int,
        help="Quality of video"
    )
    parser.add_argument(
        "url",
        type=str,
        help="Url of video, you must type it beetween quotation marks"
    )

    return parser.parse_args()


def main():
    args = cli()

    if args.video is False and args.audio is False:
        print("Select one option for to download (--audio or --video)")
        return 1

    if args.video and args.quality is None:
        video_object = Downtube((args.url).replace("'", ""))
        print(video_object.error_url("Please type the quality"))
        return 1

    if args.video and args.quality:
        video = Downtube((args.url).replace("'", ""))
        video.download_video(args.quality)

    if args.audio:
        audio = Downtube((args.url).replace("'", ""))
        audio.download_audio()


if __name__ == "__main__":
    main()
